-- Phase12: 数据质量快照表 - H2测试用
CREATE TABLE IF NOT EXISTS `data_quality_snapshot` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(50) NOT NULL COMMENT '快照标签',
  `snapshot_time` DATETIME NOT NULL COMMENT '快照时间',
  `environment` VARCHAR(50) DEFAULT NULL COMMENT '环境',
  `robot_total` BIGINT DEFAULT 0,
  `robot_cover_image_rate` DOUBLE DEFAULT 0,
  `robot_gallery_rate` DOUBLE DEFAULT 0,
  `robot_param_rate` DOUBLE DEFAULT 0,
  `robot_source_url_rate` DOUBLE DEFAULT 0,
  `robot_brand_rate` DOUBLE DEFAULT 0,
  `robot_category_rate` DOUBLE DEFAULT 0,
  `source_total` BIGINT DEFAULT 0,
  `source_healthy` BIGINT DEFAULT 0,
  `source_degraded` BIGINT DEFAULT 0,
  `source_failed` BIGINT DEFAULT 0,
  `source_unknown` BIGINT DEFAULT 0,
  `robot_fresh` BIGINT DEFAULT 0,
  `robot_aging` BIGINT DEFAULT 0,
  `robot_stale` BIGINT DEFAULT 0,
  `brand_total` BIGINT DEFAULT 0,
  `brand_website_rate` DOUBLE DEFAULT 0,
  `article_total` BIGINT DEFAULT 0,
  `article_cover_image_rate` DOUBLE DEFAULT 0,
  `article_source_url_rate` DOUBLE DEFAULT 0,
  `crawler_product_total` BIGINT DEFAULT 0,
  `crawler_product_pending_review` BIGINT DEFAULT 0,
  `crawler_product_published` BIGINT DEFAULT 0,
  `crawler_article_total` BIGINT DEFAULT 0,
  `crawler_article_pending_review` BIGINT DEFAULT 0,
  `crawler_article_published` BIGINT DEFAULT 0,
  `overall_score` DOUBLE DEFAULT 0,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);